services:
  - type: web
    name: mealia-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_WEB_CLIENT_ID
        sync: false
      - key: GOOGLE_ANDROID_CLIENT_ID
        sync: false
      - key: GOOGLE_IOS_CLIENT_ID
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SQLALCHEMY_DATABASE_URL
        sync: false