// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU6wC4NLZkyNvqXF0ZozV72CB7VwbhmEc',
    appId: '1:970236848335:web:353d1b8f9aad43eab66fba',
    messagingSenderId: '970236848335',
    projectId: 'mealiav2',
    authDomain: 'mealiav2.firebaseapp.com',
    storageBucket: 'mealiav2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZgtvNDAVFDd8C_AKHlv_EU3FDFbRYE8',
    appId: '1:970236848335:android:2a65cdbba7da1380b66fba',
    messagingSenderId: '970236848335',
    projectId: 'mealiav2',
    storageBucket: 'mealiav2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1KoNPPOE7o0olLsDbkZOFwPKazR_27iM',
    appId: '1:970236848335:ios:46beb06fedd5b991b66fba',
    messagingSenderId: '970236848335',
    projectId: 'mealiav2',
    storageBucket: 'mealiav2.firebasestorage.app',
    androidClientId: '970236848335-i0tvsjmvpa8bqisok1svcvfhqvmct4e0.apps.googleusercontent.com',
    iosClientId: '970236848335-p0l27kbi9b7q3g9ackgheem6mm0rqk68.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1KoNPPOE7o0olLsDbkZOFwPKazR_27iM',
    appId: '1:970236848335:ios:46beb06fedd5b991b66fba',
    messagingSenderId: '970236848335',
    projectId: 'mealiav2',
    storageBucket: 'mealiav2.firebasestorage.app',
    androidClientId: '970236848335-i0tvsjmvpa8bqisok1svcvfhqvmct4e0.apps.googleusercontent.com',
    iosClientId: '970236848335-p0l27kbi9b7q3g9ackgheem6mm0rqk68.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU6wC4NLZkyNvqXF0ZozV72CB7VwbhmEc',
    appId: '1:970236848335:web:eaa2c87fee67a279b66fba',
    messagingSenderId: '970236848335',
    projectId: 'mealiav2',
    authDomain: 'mealiav2.firebaseapp.com',
    storageBucket: 'mealiav2.firebasestorage.app',
  );
}
